syntax on

set list listchars=tab:\|\ 
highlight Whitespace cterm=underline gui=underline ctermbg=NONE guibg=NONE ctermfg=yellow guifg=yellow
autocmd ColorScheme * highlight Whitespace gui=underline ctermbg=NONE guibg=NONE ctermfg=yellow guifg=yellow
match Whitespace /  \+/

set showmatch " show matching brackets
set ignorecase " do case-insensitive matching

if has("syntax")
    syntax on
endif

set background=dark
set number

