" You'll need to add the following to your ~/.vimrc so that pathogen will be loaded
" properly. Filetype detection must be off when you run the commands so its best to
" You'll need to add the following to your ~/.vimrc so that pathogen will be loaded
" execute them first:
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype on

syntax on

let mapleader = ","
let g:CommandTMaxHeight=25
imap ii <Esc>

map <S-Enter> O<Esc>
map <CR> o<Esc>

"123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 

set hlsearch
set colorcolumn=79

" The following lines will put a grey highlight over characters that exceed a
" wideth of 79 characters.
" augroup vimrc_autocmds
"   autocmd BufEnter * highlight OverLength ctermbg=darkred guibg=#592929
"   autocmd BufEnter * match OverLength /\%80v.*/
" augroup END

set nocompatible
set ruler
set number
set shellcmdflag=-ic
set list
set expandtab
set tabstop=4
set softtabstop=4
nmap <C-k> ddkP
nmap <C-j> ddp
vmap <C-k> xkP`[V`]
vmap <C-j> xp`[V`]

au! BufWritePost vimrc source %
colorscheme vividchalk
"colorscheme jellybeans
"colorscheme gummybears
"colorscheme solarized
"colorscheme distinguished
"colorscheme ir_black

